include:
  - "https://gitlab.mobilityservices.io/infra/gitlab-ci/raw/master/.otonomousmobility.com.yaml"
  - 'https://gitlab.mobilityservices.io/infra/gitlab-ci/raw/master/afm-nodejs.yaml'


variables:
  SKIP_PREFLIGHT_CHECK: "true"