include:
  - "https://gitlab.mobilityservices.io/infra/gitlab-ci/raw/master/.otonomousmobility.com.yaml"

variables:
  SKIP_PREFLIGHT_CHECK: "true"

lint:
  stage: test
  image: node:10-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm config set //nexus.mobilityservices.io/repository/npm-das/:_authToken ${NPM_TOKEN} 
    - npm config set @das:registry https://nexus.mobilityservices.io/repository/npm-das/

    - npm config set unsafe-perm true
    - npm i
  script:
    - npm run lint

test:
  stage: test
  image: node:10-alpine
  cache:
    paths:
      - node_modules/
  variables:
    NODE_ENV: test
    NODE_CONFIG_ENV: test
  before_script:
    - npm config set //nexus.mobilityservices.io/repository/npm-das/:_authToken ${NPM_TOKEN}
    - npm config set @das:registry https://nexus.mobilityservices.io/repository/npm-das/
      
    - npm config set unsafe-perm true
    - npm i
  script:
    - npm run test
  coverage: /^Coverage. ([^%]+)/
  
  # disabled jobs
sast:
  stage: test
  script:
    - echo "disabled"
  only:
    - disabled-afm-job

terraform:statuscake:backup:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job

terraform:statuscake:plan:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job
    
terraform:statuscake:apply:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job

terraform:statuscake:apply:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job

terraform:destroy:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job

dependency_scanning:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job
    
    
license_management:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job

code_quality:
  stage: build
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job
    
container_scanning:
  stage: test
  script:
    - echo "disabled"
  only:
    - disabled-frontend-job
